apiVersion: v1
kind: Namespace
metadata:
  name: echoserver-ns
  labels:
    istio.io/rev: 1-16-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-app
  namespace: echoserver-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver-app
  template:
    metadata:
      labels:
        app: echoserver-app
        version: "1.4"
    spec:
      containers:
      - name: echoserver-app
        image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-svc
  namespace: echoserver-ns
spec:
  selector:
    app: echoserver-app
  ports:
  - name: http-echoserver
    port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoserver-vs
  namespace: echoserver-ns
spec:
  hosts:
  - "meu-istio.com.br"
  gateways:
  - istio-system/internal-gateway
  http:
  - match:
    - uri:
        prefix: /echo
    route:
    - destination:
        host: echoserver-svc.echoserver-ns.svc.cluster.local
        port:
          number: 80
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: echoserver-app
  namespace: echoserver-ns
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echoserver-dr
  namespace: echoserver-ns
spec:
  host: echoserver-svc.echoserver-ns.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
